[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 4.4.0-177-generic (buildd@lgw01-amd64-035) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) ) #207-Ubuntu SMP Mon Mar 16 01:16:10 UTC 2020 (Ubuntu 4.4.0-177.207-generic 4.4.214)
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-4.4.0-177-generic root=UUID=028dcf64-728a-43a3-8470-fbd74a027bdf ro console=tty1 console=ttyS0
[    0.000000] KERNEL supported cpus:
[    0.000000]   Intel GenuineIntel
[    0.000000]   AMD AuthenticAMD
[    0.000000]   Centaur CentaurHauls
[    0.000000] x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
[    0.000000] x86/fpu: Supporting XSAVE feature 0x01: 'x87 floating point registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x02: 'SSE registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x04: 'AVX registers'
[    0.000000] x86/fpu: Enabled xstate features 0x7, context size is 832 bytes, using 'standard' format.
[    0.000000] e820: BIOS-provided physical RAM map:
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009fbff] usable
[    0.000000] BIOS-e820: [mem 0x000000000009fc00-0x000000000009ffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000000f0000-0x00000000000fffff] reserved
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x000000003ffeffff] usable
[    0.000000] BIOS-e820: [mem 0x000000003fff0000-0x000000003fffffff] ACPI data
[    0.000000] BIOS-e820: [mem 0x00000000fec00000-0x00000000fec00fff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000fee00000-0x00000000fee00fff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000fffc0000-0x00000000ffffffff] reserved
[    0.000000] NX (Execute Disable) protection: active
[    0.000000] SMBIOS 2.5 present.
[    0.000000] Hypervisor detected: KVM
[    0.000000] e820: last_pfn = 0x3fff0 max_arch_pfn = 0x400000000
[    0.000000] MTRR: Disabled
[    0.000000] x86/PAT: MTRRs disabled, skipping PAT initialization too.
[    0.000000] CPU MTRRs all blank - virtualized system.
[    0.000000] x86/PAT: Configuration [0-7]: WB  WT  UC- UC  WB  WT  UC- UC  
[    0.000000] found SMP MP-table at [mem 0x0009fff0-0x0009ffff] mapped at [ffff88000009fff0]
[    0.000000] Scanning 1 areas for low memory corruption
[    0.000000] RAMDISK: [mem 0x361cc000-0x370ddfff]
[    0.000000] ACPI: Early table checksum verification disabled
[    0.000000] ACPI: RSDP 0x00000000000E0000 000024 (v02 VBOX  )
[    0.000000] ACPI: XSDT 0x000000003FFF0030 00003C (v01 VBOX   VBOXXSDT 00000001 ASL  00000061)
[    0.000000] ACPI: FACP 0x000000003FFF00F0 0000F4 (v04 VBOX   VBOXFACP 00000001 ASL  00000061)
[    0.000000] ACPI: DSDT 0x000000003FFF0470 0022EA (v02 VBOX   VBOXBIOS 00000002 INTL 20100528)
[    0.000000] ACPI: FACS 0x000000003FFF0200 000040
[    0.000000] ACPI: FACS 0x000000003FFF0200 000040
[    0.000000] ACPI: APIC 0x000000003FFF0240 00005C (v02 VBOX   VBOXAPIC 00000001 ASL  00000061)
[    0.000000] ACPI: SSDT 0x000000003FFF02A0 0001CC (v01 VBOX   VBOXCPUT 00000002 INTL 20100528)
[    0.000000] No NUMA configuration found
[    0.000000] Faking a node at [mem 0x0000000000000000-0x000000003ffeffff]
[    0.000000] NODE_DATA(0) allocated [mem 0x3ffeb000-0x3ffeffff]
[    0.000000] kvm-clock: Using msrs 4b564d01 and 4b564d00
[    0.000000] kvm-clock: cpu 0, msr 0:3ffe3001, primary cpu clock
[    0.000000] kvm-clock: using sched offset of 3635993706 cycles
[    0.000000] clocksource: kvm-clock: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000001000-0x0000000000ffffff]
[    0.000000]   DMA32    [mem 0x0000000001000000-0x000000003ffeffff]
[    0.000000]   Normal   empty
[    0.000000]   Device   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000001000-0x000000000009efff]
[    0.000000]   node   0: [mem 0x0000000000100000-0x000000003ffeffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000001000-0x000000003ffeffff]
[    0.000000] ACPI: PM-Timer IO Port: 0x4008
[    0.000000] IOAPIC[0]: apic_id 2, version 32, address 0xfec00000, GSI 0-23
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 0 global_irq 2 dfl dfl)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 9 global_irq 9 low level)
[    0.000000] Using ACPI (MADT) for SMP configuration information
[    0.000000] smpboot: Allowing 2 CPUs, 0 hotplug CPUs
[    0.000000] PM: Registered nosave memory: [mem 0x00000000-0x00000fff]
[    0.000000] PM: Registered nosave memory: [mem 0x0009f000-0x0009ffff]
[    0.000000] PM: Registered nosave memory: [mem 0x000a0000-0x000effff]
[    0.000000] PM: Registered nosave memory: [mem 0x000f0000-0x000fffff]
[    0.000000] e820: [mem 0x40000000-0xfebfffff] available for PCI devices
[    0.000000] Booting paravirtualized kernel on KVM
[    0.000000] clocksource: refined-jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645519600211568 ns
[    0.000000] setup_percpu: NR_CPUS:512 nr_cpumask_bits:512 nr_cpu_ids:2 nr_node_ids:1
[    0.000000] PERCPU: Embedded 33 pages/cpu @ffff88003fc00000 s95448 r8192 d31528 u1048576
[    0.000000] Built 1 zonelists in Node order, mobility grouping on.  Total pages: 257912
[    0.000000] Policy zone: DMA32
[    0.000000] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.4.0-177-generic root=UUID=028dcf64-728a-43a3-8470-fbd74a027bdf ro console=tty1 console=ttyS0
[    0.000000] PID hash table entries: 4096 (order: 3, 32768 bytes)
[    0.000000] Memory: 997120K/1048120K available (8626K kernel code, 1336K rwdata, 4036K rodata, 1488K init, 1292K bss, 51000K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=2, Nodes=1
[    0.000000] Kernel/User page tables isolation: enabled
[    0.000000] Hierarchical RCU implementation.
[    0.000000] 	Build-time adjustment of leaf fanout to 64.
[    0.000000] 	RCU restricting CPUs from NR_CPUS=512 to nr_cpu_ids=2.
[    0.000000] RCU: Adjusting geometry for rcu_fanout_leaf=64, nr_cpu_ids=2
[    0.000000] NR_IRQS:33024 nr_irqs:440 16
[    0.000000] Console: colour VGA+ 80x25
[    0.000000] console [tty1] enabled
[    0.000000] console [ttyS0] enabled
[    0.000000] tsc: Detected 2793.532 MHz processor
[    0.166709] Calibrating delay loop (skipped) preset value.. 5587.06 BogoMIPS (lpj=11174128)
[    0.168528] pid_max: default: 32768 minimum: 301
[    0.169714] ACPI: Core revision 20150930
[    0.171240] ACPI: 2 ACPI AML tables successfully acquired and loaded
[    0.172723] Security Framework initialized
[    0.173704] Yama: becoming mindful.
[    0.174554] AppArmor: AppArmor initialized
[    0.175489] Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes)
[    0.179018] Inode-cache hash table entries: 65536 (order: 7, 524288 bytes)
[    0.180567] Mount-cache hash table entries: 2048 (order: 2, 16384 bytes)
[    0.182675] Mountpoint-cache hash table entries: 2048 (order: 2, 16384 bytes)
[    0.184448] Initializing cgroup subsys io
[    0.185519] Initializing cgroup subsys memory
[    0.186599] Initializing cgroup subsys devices
[    0.187702] Initializing cgroup subsys freezer
[    0.188903] Initializing cgroup subsys net_cls
[    0.189890] Initializing cgroup subsys perf_event
[    0.191047] Initializing cgroup subsys net_prio
[    0.192155] Initializing cgroup subsys hugetlb
[    0.193279] Initializing cgroup subsys pids
[    0.195347] mce: CPU supports 0 MCE banks
[    0.196413] Last level iTLB entries: 4KB 1024, 2MB 1024, 4MB 1024
[    0.197859] Last level dTLB entries: 4KB 1024, 2MB 1024, 4MB 1024, 1GB 4
[    0.199360] Spectre V1 : Mitigation: usercopy/swapgs barriers and __user pointer sanitization
[    0.201281] Spectre V2 : Mitigation: Full generic retpoline
[    0.202586] Spectre V2 : Spectre v2 / SpectreRSB mitigation: Filling RSB on context switch
[    0.204607] Speculative Store Bypass: Vulnerable
[    0.205742] MDS: Mitigation: Clear CPU buffers
[    0.209222] Freeing SMP alternatives memory: 36K
[    0.215122] ftrace: allocating 32304 entries in 127 pages
[    0.267381] smpboot: APIC(0) Converting physical 0 to logical package 0
[    0.268943] smpboot: Max logical packages: 1
[    0.272560] x2apic enabled
[    0.273561] Switched APIC routing to physical x2apic.
[    0.275654] ..TIMER: vector=0x30 apic1=0 pin1=2 apic2=-1 pin2=-1
[    0.385307] smpboot: CPU0: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (family: 0x6, model: 0x46, stepping: 0x1)
[    0.387898] Performance Events: unsupported p6 CPU model 70 no PMU driver, software events only.
[    0.399453] KVM setup paravirtual spinlock
[    0.400907] x86: Booting SMP configuration:
[    0.402445] .... node  #0, CPUs:      #1
[    0.403409] kvm-clock: cpu 1, msr 0:3ffe3041, secondary cpu clock
[    0.405374] mce: CPU supports 0 MCE banks
[    0.408178] x86: Booted up 1 node, 2 CPUs
[    0.409506] smpboot: Total of 2 processors activated (11174.12 BogoMIPS)
[    0.411459] devtmpfs: initialized
[    0.413376] evm: security.selinux
[    0.414176] evm: security.SMACK64
[    0.415053] evm: security.SMACK64EXEC
[    0.415875] evm: security.SMACK64TRANSMUTE
[    0.417035] evm: security.SMACK64MMAP
[    0.417952] evm: security.ima
[    0.418665] evm: security.capability
[    0.419680] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.421787] futex hash table entries: 512 (order: 3, 32768 bytes)
[    0.423177] pinctrl core: initialized pinctrl subsystem
[    0.424313] RTC time:  7:25:23, date: 05/22/20
[    0.425453] NET: Registered protocol family 16
[    0.438156] cpuidle: using governor ladder
[    0.450577] cpuidle: using governor menu
[    0.451701] PCCT header not found.
[    0.452795] ACPI: bus type PCI registered
[    0.453778] acpiphp: ACPI Hot Plug PCI Controller Driver version: 0.5
[    0.455377] PCI: Using configuration type 1 for base access
[    0.470831] ACPI: Added _OSI(Module Device)
[    0.471787] ACPI: Added _OSI(Processor Device)
[    0.472862] ACPI: Added _OSI(3.0 _SCP Extensions)
[    0.474039] ACPI: Added _OSI(Processor Aggregator Device)
[    0.476099] ACPI: Executed 1 blocks of module-level executable AML code
[    0.479499] ACPI: Interpreter enabled
[    0.480538] ACPI: (supports S0 S5)
[    0.481379] ACPI: Using IOAPIC for interrupt routing
[    0.482501] PCI: Using host bridge windows from ACPI; if necessary, use "pci=nocrs" and report a bug
[    0.488286] ACPI: PCI Root Bridge [PCI0] (domain 0000 [bus 00-ff])
[    0.489864] acpi PNP0A03:00: _OSC: OS supports [ASPM ClockPM Segments MSI]
[    0.491529] acpi PNP0A03:00: _OSC: not requesting OS control; OS requires [ExtendedConfig ASPM ClockPM MSI]
[    0.493930] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
[    0.496639] PCI host bridge to bus 0000:00
[    0.497549] pci_bus 0000:00: root bus resource [io  0x0000-0x0cf7 window]
[    0.498881] pci_bus 0000:00: root bus resource [io  0x0d00-0xffff window]
[    0.500239] pci_bus 0000:00: root bus resource [mem 0x000a0000-0x000bffff window]
[    0.501994] pci_bus 0000:00: root bus resource [mem 0x40000000-0xfdffffff window]
[    0.503782] pci_bus 0000:00: root bus resource [bus 00-ff]
[    0.507412] pci 0000:00:01.1: legacy IDE quirk: reg 0x10: [io  0x01f0-0x01f7]
[    0.508902] pci 0000:00:01.1: legacy IDE quirk: reg 0x14: [io  0x03f6]
[    0.510184] pci 0000:00:01.1: legacy IDE quirk: reg 0x18: [io  0x0170-0x0177]
[    0.511765] pci 0000:00:01.1: legacy IDE quirk: reg 0x1c: [io  0x0376]
[    0.533965] pci 0000:00:07.0: quirk: [io  0x4000-0x403f] claimed by PIIX4 ACPI
[    0.535731] pci 0000:00:07.0: quirk: [io  0x4100-0x410f] claimed by PIIX4 SMB
[    0.542997] ACPI: PCI Interrupt Link [LNKA] (IRQs 5 9 10 *11)
[    0.544711] ACPI: PCI Interrupt Link [LNKB] (IRQs 5 9 *10 11)
[    0.546908] ACPI: PCI Interrupt Link [LNKC] (IRQs 5 *9 10 11)
[    0.548721] ACPI: PCI Interrupt Link [LNKD] (IRQs 5 9 10 *11)
[    0.550274] ACPI: Enabled 2 GPEs in block 00 to 07
[    0.551739] vgaarb: setting as boot device: PCI:0000:00:02.0
[    0.553197] vgaarb: device added: PCI:0000:00:02.0,decodes=io+mem,owns=io+mem,locks=none
[    0.554979] vgaarb: loaded
[    0.555611] vgaarb: bridge control possible 0000:00:02.0
[    0.556938] SCSI subsystem initialized
[    0.558044] ACPI: bus type USB registered
[    0.559063] usbcore: registered new interface driver usbfs
[    0.560262] usbcore: registered new interface driver hub
[    0.561676] usbcore: registered new device driver usb
[    0.563107] PCI: Using ACPI for IRQ routing
[    0.564407] NetLabel: Initializing
[    0.565157] NetLabel:  domain hash size = 128
[    0.566418] NetLabel:  protocols = UNLABELED CIPSOv4
[    0.568914] NetLabel:  unlabeled traffic allowed by default
[    0.570275] amd_nb: Cannot enumerate AMD northbridges
[    0.571432] clocksource: Switched to clocksource kvm-clock
[    0.580321] AppArmor: AppArmor Filesystem Enabled
[    0.581465] pnp: PnP ACPI init
[    0.583361] pnp: PnP ACPI: found 3 devices
[    0.594123] clocksource: acpi_pm: mask: 0xffffff max_cycles: 0xffffff, max_idle_ns: 2085701024 ns
[    0.596152] NET: Registered protocol family 2
[    0.597408] TCP established hash table entries: 8192 (order: 4, 65536 bytes)
[    0.599002] TCP bind hash table entries: 8192 (order: 5, 131072 bytes)
[    0.600420] TCP: Hash tables configured (established 8192 bind 8192)
[    0.601734] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.602943] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.604504] NET: Registered protocol family 1
[    0.605484] pci 0000:00:00.0: Limiting direct PCI/PCI transfers
[    0.606902] pci 0000:00:01.0: Activating ISA DMA hang workarounds
[    0.608333] Unpacking initramfs...
[    0.812251] Freeing initrd memory: 15432K
[    0.813214] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x284462ec54c, max_idle_ns: 440795344772 ns
[    0.815585] platform rtc_cmos: registered platform RTC device (no PNP device found)
[    0.817540] Scanning for low memory corruption every 60 seconds
[    0.819235] audit: initializing netlink subsys (disabled)
[    0.820506] audit: type=2000 audit(1590132328.243:1): initialized
[    0.821909] Initialise system trusted keyring
[    0.823058] HugeTLB registered 2 MB page size, pre-allocated 0 pages
[    0.825700] zbud: loaded
[    0.826666] VFS: Disk quotas dquot_6.6.0
[    0.827607] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    0.829400] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.830914] fuse init (API version 7.23)
[    0.832027] Key type big_key registered
[    0.833010] Allocating IMA MOK and blacklist keyrings.
[    0.835883] Key type asymmetric registered
[    0.836905] Asymmetric key parser 'x509' registered
[    0.837926] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 249)
[    0.839607] io scheduler noop registered
[    0.840448] io scheduler deadline registered (default)
[    0.841568] io scheduler cfq registered
[    0.842456] pci_hotplug: PCI Hot Plug PCI Core version: 0.5
[    0.843569] pciehp: PCI Express Hot Plug Controller Driver version: 0.4
[    0.845389] ACPI: AC Adapter [AC] (on-line)
[    0.846580] input: Power Button as /devices/LNXSYSTM:00/LNXPWRBN:00/input/input0
[    0.848201] ACPI: Power Button [PWRF]
[    0.849102] input: Sleep Button as /devices/LNXSYSTM:00/LNXSLPBN:00/input/input1
[    0.850956] ACPI: Sleep Button [SLPF]
[    0.853175] ACPI: Battery Slot [BAT0] (battery present)
[    0.854323] GHES: HEST is not enabled!
[    0.855333] Serial: 8250/16550 driver, 32 ports, IRQ sharing enabled
[    0.877647] 00:02: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a 16550A
[    0.880279] Linux agpgart interface v0.103
[    0.884919] loop: module loaded
[    0.886620] scsi host0: ata_piix
[    0.887779] scsi host1: ata_piix
[    0.888658] ata1: PATA max UDMA/33 cmd 0x1f0 ctl 0x3f6 bmdma 0xd000 irq 14
[    0.890147] ata2: PATA max UDMA/33 cmd 0x170 ctl 0x376 bmdma 0xd008 irq 15
[    0.892143] libphy: Fixed MDIO Bus: probed
[    0.893136] tun: Universal TUN/TAP device driver, 1.6
[    0.894396] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[    0.896069] PPP generic driver version 2.4.2
[    0.897318] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    0.898649] ehci-pci: EHCI PCI platform driver
[    0.899764] ehci-platform: EHCI generic platform driver
[    0.900971] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    0.902175] ohci-pci: OHCI PCI platform driver
[    0.903134] ohci-platform: OHCI generic platform driver
[    0.904273] uhci_hcd: USB Universal Host Controller Interface driver
[    0.906010] i8042: PNP: PS/2 Controller [PNP0303:PS2K,PNP0f03:PS2M] at 0x60,0x64 irq 1,12
[    0.908329] serio: i8042 KBD port at 0x60,0x64 irq 1
[    0.909364] serio: i8042 AUX port at 0x60,0x64 irq 12
[    0.910555] mousedev: PS/2 mouse device common for all mice
[    0.912132] rtc_cmos rtc_cmos: rtc core: registered rtc_cmos as rtc0
[    0.913536] rtc_cmos rtc_cmos: alarms up to one day, 114 bytes nvram
[    0.914810] i2c /dev entries driver
[    0.915702] input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input2
[    0.917837] device-mapper: uevent: version 1.0.3
[    0.918978] device-mapper: ioctl: 4.34.0-ioctl (2015-10-28) initialised: dm-devel@redhat.com
[    0.920870] ledtrig-cpu: registered to indicate activity on CPUs
[    0.922844] NET: Registered protocol family 10
[    0.924197] NET: Registered protocol family 17
[    0.925146] Key type dns_resolver registered
[    0.926232] registered taskstats version 1
[    0.927282] Loading compiled-in X.509 certificates
[    0.928844] Loaded X.509 cert 'Build time autogenerated kernel key: a048edf52b07f04005c7780de0f875c713550332'
[    0.930888] zswap: loaded using pool lzo/zbud
[    0.933540] Key type trusted registered
[    0.937466] Key type encrypted registered
[    0.940182] AppArmor: AppArmor sha1 policy hashing enabled
[    0.941276] ima: No TPM chip found, activating TPM-bypass!
[    0.942363] ima: Allocated hash algorithm: sha1
[    0.943410] evm: HMAC attrs: 0x1
[    0.944522]   Magic number: 4:761:420
[    0.945517] rtc_cmos rtc_cmos: setting system clock to 2020-05-22 07:25:23 UTC (1590132323)
[    0.947556] BIOS EDD facility v0.16 2004-Jun-25, 0 devices found
[    0.948812] EDD information not available.
[    1.052894] Freeing unused kernel memory: 1488K
[    1.053889] Write protecting the kernel read-only data: 14336k
[    1.055895] Freeing unused kernel memory: 1604K
[    1.057206] Freeing unused kernel memory: 60K
Loading, please wait...
starting version 229
[    1.070846] random: systemd-udevd: uninitialized urandom read (16 bytes read, 2 bits of entropy available)
[    1.071348] random: udevadm: uninitialized urandom read (16 bytes read, 2 bits of entropy available)
[    1.071365] random: udevadm: uninitialized urandom read (16 bytes read, 2 bits of entropy available)
[    1.076786] random: systemd-udevd: uninitialized urandom read (16 bytes read, 2 bits of entropy available)
[    1.077939] random: udevadm: uninitialized urandom read (16 bytes read, 2 bits of entropy available)
[    1.077976] random: udevadm: uninitialized urandom read (16 bytes read, 2 bits of entropy available)
[    1.078091] random: udevadm: uninitialized urandom read (16 bytes read, 2 bits of entropy available)
[    1.078129] random: udevadm: uninitialized urandom read (16 bytes read, 2 bits of entropy available)
[    1.078164] random: udevadm: uninitialized urandom read (16 bytes read, 2 bits of entropy available)
[    1.078199] random: udevadm: uninitialized urandom read (16 bytes read, 2 bits of entropy available)
[    1.117747] e1000: Intel(R) PRO/1000 Network Driver - version 7.3.21-k8-NAPI
[    1.119259] e1000: Copyright (c) 1999-2006 Intel Corporation.
[    1.122596] Fusion MPT base driver 3.04.20
[    1.123467] Copyright (c) 1999-2008 LSI Corporation
[    1.148427] Fusion MPT SPI Host driver 3.04.20
[    1.152382] AVX2 version of gcm_enc/dec engaged.
[    1.153643] AES CTR mode by8 optimization enabled
[    1.346764] input: ImExPS/2 Generic Explorer Mouse as /devices/platform/i8042/serio1/input/input4
[    1.516555] e1000 0000:00:03.0 eth0: (PCI:33MHz:32-bit) 02:dd:a3:75:e5:c1
[    1.517930] e1000 0000:00:03.0 eth0: Intel(R) PRO/1000 Network Connection
[    1.520129] mptbase: ioc0: Initiating bringup
[    1.520606] e1000 0000:00:03.0 enp0s3: renamed from eth0
[    1.595373] ioc0: LSI53C1030 A0: Capabilities={Initiator}
[    2.362111] scsi host2: ioc0: LSI53C1030 A0, FwRev=00000000h, Ports=1, MaxQ=256, IRQ=20
[    3.372679] scsi 2:0:0:0: Direct-Access     VBOX     HARDDISK         1.0  PQ: 0 ANSI: 5
[    3.374409] scsi target2:0:0: Beginning Domain Validation
[    3.377249] scsi target2:0:0: Domain Validation skipping write tests
[    3.378499] scsi target2:0:0: Ending Domain Validation
[    3.379656] scsi target2:0:0: asynchronous
[    3.381293] scsi 2:0:1:0: Direct-Access     VBOX     HARDDISK         1.0  PQ: 0 ANSI: 5
[    3.383075] scsi target2:0:1: Beginning Domain Validation
[    3.385821] scsi target2:0:1: Domain Validation skipping write tests
[    3.387445] scsi target2:0:1: Ending Domain Validation
[    3.388695] scsi target2:0:1: asynchronous
[    3.405538] sd 2:0:0:0: [sda] 20971520 512-byte logical blocks: (10.7 GB/10.0 GiB)
[    3.407437] sd 2:0:0:0: Attached scsi generic sg0 type 0
[    3.409411] sd 2:0:1:0: Attached scsi generic sg1 type 0
[    3.410508] sd 2:0:1:0: [sdb] 20480 512-byte logical blocks: (10.5 MB/10.0 MiB)
[    3.412247] sd 2:0:0:0: [sda] Write Protect is off
[    3.413524] sd 2:0:0:0: [sda] Incomplete mode parameter data
[    3.414820] sd 2:0:0:0: [sda] Assuming drive cache: write through
[    3.416215] sd 2:0:1:0: [sdb] Write Protect is off
[    3.417702] sd 2:0:1:0: [sdb] Incomplete mode parameter data
[    3.419194] sd 2:0:1:0: [sdb] Assuming drive cache: write through
[    3.424011]  sda: sda1
[    3.425615] sd 2:0:0:0: [sda] Attached SCSI disk
[    3.427295] sd 2:0:1:0: [sdb] Attached SCSI disk
Begin: Loading essential drivers ... [    4.733871] md: linear personality registered for level -1
[    4.737053] md: multipath personality registered for level -4
[    4.740866] md: raid0 personality registered for level 0
[    4.745504] md: raid1 personality registered for level 1
[    4.815479] raid6: sse2x1   gen() 11306 MB/s
[    4.883498] raid6: sse2x1   xor()  8724 MB/s
[    4.951498] raid6: sse2x2   gen() 14177 MB/s
[    5.019628] raid6: sse2x2   xor()  9537 MB/s
[    5.087481] raid6: sse2x4   gen() 15734 MB/s
[    5.155665] raid6: sse2x4   xor() 11523 MB/s
[    5.223517] raid6: avx2x1   gen() 21655 MB/s
[    5.291486] raid6: avx2x2   gen() 25548 MB/s
[    5.359479] raid6: avx2x4   gen() 29125 MB/s
[    5.360390] raid6: using algorithm avx2x4 gen() 29125 MB/s
[    5.361538] raid6: using avx2x2 recovery algorithm
[    5.368323] xor: automatically using best checksumming function:
[    5.407473]    avx       : 29923.000 MB/sec
[    5.410332] async_tx: api initialized (async)
[    5.420789] md: raid6 personality registered for level 6
[    5.421917] md: raid5 personality registered for level 5
[    5.423301] md: raid4 personality registered for level 4
[    5.430308] md: raid10 personality registered for level 10
done.
Begin: Running /scripts/init-premount ... done.
Begin: Mounting root file system ... Begin: Running /scripts/local-top ... done.
Begin: Running /scripts/local-premount ... [    5.459264] Btrfs loaded
Scanning for Btrfs filesystems
done.
Warning: fsck not present, so skipping root file system
[    5.486843] EXT4-fs (sda1): INFO: recovery required on readonly filesystem
[    5.488221] EXT4-fs (sda1): write access will be enabled during recovery
[    5.539432] EXT4-fs (sda1): recovery complete
[    5.540637] EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)
done.
Begin: Running /scripts/local-bottom ... done.
Begin: Running /scripts/init-bottom ... done.
[    5.626395] systemd[1]: systemd 229 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN)
[    5.630202] systemd[1]: Detected virtualization oracle.
[    5.631374] systemd[1]: Detected architecture x86-64.

Welcome to [1mUbuntu 16.04.6 LTS[0m!

[    5.634493] systemd[1]: Set hostname to <ubuntu-xenial>.
[    5.832384] systemd[1]: Listening on LVM2 metadata daemon socket.
[[0;32m  OK  [0m] Listening on LVM2 metadata daemon socket.
[    5.834949] systemd[1]: Reached target Encrypted Volumes.
[[0;32m  OK  [0m] Reached target Encrypted Volumes.
[    5.837611] systemd[1]: Reached target System Time Synchronized.
[[0;32m  OK  [0m] Reached target System Time Synchronized.
[    5.999839] systemd[1]: Reached target User and Group Name Lookups.
[[0;32m  OK  [0m] Reached target User and Group Name Lookups.
[    6.002442] systemd[1]: Listening on udev Control Socket.
[[0;32m  OK  [0m] Listening on udev Control Socket.
[    6.015787] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[[0;32m  OK  [0m] Set up automount Arbitrary Executab...ats File System Automount Point.
[    6.019399] systemd[1]: Listening on Device-mapper event daemon FIFOs.
[[0;32m  OK  [0m] Listening on Device-mapper event daemon FIFOs.
[    6.021935] systemd[1]: Listening on Journal Socket (/dev/log).
[[0;32m  OK  [0m] Listening on Journal Socket (/dev/log).
[    6.024469] systemd[1]: Listening on LVM2 poll daemon socket.
[[0;32m  OK  [0m] Listening on LVM2 poll daemon socket.
[    6.329794] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[[0;32m  OK  [0m] Started Forward Password Requests to Wall Directory Watch.
[    6.333028] systemd[1]: Created slice System Slice.
[[0;32m  OK  [0m] Created slice System Slice.
[    6.335255] systemd[1]: Created slice system-serial\x2dgetty.slice.
[[0;32m  OK  [0m] Created slice system-serial\x2dgetty.slice.
[    6.338140] systemd[1]: Started Trigger resolvconf update for networkd DNS.
[[0;32m  OK  [0m] Started Trigger resolvconf update for networkd DNS.
[    6.341271] systemd[1]: Created slice User and Session Slice.
[[0;32m  OK  [0m] Created slice User and Session Slice.
[    6.343615] systemd[1]: Reached target Slices.
[[0;32m  OK  [0m] Reached target Slices.
[    6.345526] systemd[1]: Listening on Syslog Socket.
[[0;32m  OK  [0m] Listening on Syslog Socket.
[    6.347558] systemd[1]: Listening on Journal Socket.
[[0;32m  OK  [0m] Listening on Journal Socket.
[    6.360038] systemd[1]: Starting Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
         Starting Monitoring of LVM2 mirrors... dmeventd or progress polling...
[    6.365057] systemd[1]: Mounting POSIX Message Queue File System...
         Mounting POSIX Message Queue File System...
[    6.368367] systemd[1]: Starting Nameserver information manager...
         Starting Nameserver information manager...
[    6.372967] systemd[1]: Starting Uncomplicated firewall...
         Starting Uncomplicated firewall...
[    6.375909] systemd[1]: Starting Set console keymap...
         Starting Set console keymap...
[    6.381650] systemd[1]: Starting Load Kernel Modules...
         Starting Load Kernel Modules...
[    6.387291] systemd[1]: Mounting Debug File System...
         Mounting Debug File System...
[    6.390036] systemd[1]: Starting Remount Root and Kernel File Systems...
[    6.394105] Loading iSCSI transport class v2.0-870.
[    6.395242] EXT4-fs (sda1): re-mounted. Opts: (null)
         Starting Remount Root and Kernel File Systems...
[    6.398206] systemd[1]: Starting Create list of required static device nodes for the current kernel...
         Starting Create list of required st... nodes for the current kernel...
[    6.404421] systemd[1]: Mounting Huge Pages File System...
         Mounting Huge Pages File System...
[    6.407110] systemd[1]: Listening on udev Kernel Socket.
[    6.408656] iscsi: registered transport (tcp)
[[0;32m  OK  [0m] Listening on udev Kernel Socket.
[    6.411282] systemd[1]: Listening on Journal Audit Socket.
[[0;32m  OK  [0m] Listening on Journal Audit Socket.
[    6.414392] systemd[1]: Starting Journal Service...
         Starting Journal Service...
[    6.416989] systemd[1]: Listening on /dev/initctl Compatibility Named Pipe.
[[0;32m  OK  [0m] Listening on /dev/initctl Compatibility Named Pipe.
[    6.420557] systemd[1]: Mounted POSIX Message Queue File System.
[[0;32m  OK  [0m] Mounted POSIX Message Queue File System.
[    6.428340] systemd[1]: Mounted Huge Pages File System.
[[0;32m  OK  [0m] Mounted Huge Pages File System.
[    6.430966] systemd[1]: Mounted Debug File System.
[[0;32m  OK  [0m] Mounted Debug File System.
[    6.451030] iscsi: registered transport (iser)
[    6.456581] systemd[1]: Started Uncomplicated firewall.
[[0;32m  OK  [0m] Started Uncomplicated firewall.
[    6.464939] systemd[1]: Started Set console keymap.
[[0;32m  OK  [0m] Started Set console keymap.
[    6.467630] systemd[1]: Started Load Kernel Modules.
[[0;32m  OK  [0m] Started Load Kernel Modules.
[    6.469929] systemd[1]: Started Remount Root and Kernel File Systems.
[[0;32m  OK  [0m] Started Remount Root and Kernel File Systems.
[    6.473202] systemd[1]: Started Create list of required static device nodes for the current kernel.
[[0;32m  OK  [0m] Started Create list of required sta...ce nodes for the current kernel.
[    6.477122] systemd[1]: Started Nameserver information manager.
[[0;32m  OK  [0m] Started Nameserver information manager.
[    6.480910] systemd[1]: Started Journal Service.
[[0;32m  OK  [0m] Started Journal Service.
[[0;32m  OK  [0m] Started LVM2 metadata daemon.
         Starting Create Static Device Nodes in /dev...
         Activating swap /swapfile...
         Starting Flush Journal to Persistent Storage...
         Starting udev Coldplug all Devices...
         Starting Load/Save Random Seed...
         Mounting FUSE Control File System...
         Starting Apply Kernel Variables...
[[0;32m  OK  [0m] Mounted FUSE Control File System.
[[0;32m  OK  [0m] Started Create Static Device Nodes in /dev.
[[0;32m  OK  [0m] Started Load/Save Random Seed.
         Starting udev Kernel Device Manager...
[    6.541840] systemd-journald[405]: Received request to flush runtime journal from PID 1
[[0;32m  OK  [0m] Started Flush Journal to Persistent Storage.
[[0;32m  OK  [0m] Started Apply Kernel Variables.
[[0;32m  OK  [0m] Started udev Kernel Device Manager.
[[0;32m  OK  [0m] Activated swap /swapfile.
[[0;32m  OK  [0m] Reached target Swap.
[[0;32m  OK  [0m] Started udev Coldplug all Devices.
[[0;32m  OK  [0m] Started Dispatch Password Requests to Console Directory Watch.
[[0;32m  OK  [0m] Found device /dev/ttyS0.
[[0;32m  OK  [0m] Listening on Load/Save RF Kill Switch Status /dev/rfkill Watch.
[[0;32m  OK  [0m] Started Monitoring of LVM2 mirrors,...ng dmeventd or progress polling.
[[0;32m  OK  [0m] Reached target Local File Systems (Pre).
[[0;32m  OK  [0m] Reached target Local File Systems.
         Starting Set console font and keymap...
         Starting Tell Plymouth To Write Out Runtime Data...
         Starting Create Volatile Files and Directories...
         Starting Initial cloud-init job (pre-networking)...
         Starting LSB: AppArmor initialization...
[[0;32m  OK  [0m] Started Tell Plymouth To Write Out Runtime Data.
[[0;32m  OK  [0m] Started Create Volatile Files and Directories.
         Starting Update UTMP about System Boot/Shutdown...
[[0;32m  OK  [0m] Started Update UTMP about System Boot/Shutdown.
[[0;32m  OK  [0m] Found device 82540EM Gigabit Ethern...r (PRO/1000 MT Desktop Adapter).
[[0;32m  OK  [0m] Started LSB: AppArmor initialization.
[[0;32m  OK  [0m] Started Set console font and keymap.
[[0;32m  OK  [0m] Created slice system-getty.slice.
[    7.507156] cloud-init[640]: Cloud-init v. 19.3-41-gc4735dd3-0ubuntu1~16.04.1 running 'init-local' at Fri, 22 May 2020 07:25:30 +0000. Up 7.48 seconds.
[    7.509449] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,260 - util.py[DEBUG]: Cloud-init v. 19.3-41-gc4735dd3-0ubuntu1~16.04.1 running 'init-local' at Fri, 22 May 2020 07:25:30 +0000. Up 7.48 seconds.
[    7.512197] cloud-init[640]: tee: /var/log/cloud-init-output.log: No space left on device
[    7.520345] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,261 - main.py[DEBUG]: No kernel command line url found.
[    7.522456] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,261 - main.py[DEBUG]: Closing stdin.
[    7.524169] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,268 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
[    7.526127] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,269 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 104:4
[    7.528472] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,269 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
[    7.530624] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,269 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/data/no-net
[    7.532743] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,269 - handlers.py[DEBUG]: start: init-local/check-cache: attempting to read from cache [check]
[    7.535272] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,270 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
[    7.537571] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,270 - util.py[DEBUG]: Read 8192 bytes from /var/lib/cloud/instance/obj.pkl
[    7.539527] cloud-init[640]: 2020-05-22 07:25:30,273 - util.py[WARNING]: Failed loading pickled blob from /var/lib/cloud/instance/obj.pkl
[    7.541564] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,273 - util.py[WARNING]: Failed loading pickled blob from /var/lib/cloud/instance/obj.pkl
[    7.548576] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,273 - util.py[DEBUG]: Failed loading pickled blob from /var/lib/cloud/instance/obj.pkl
[    7.556922] cloud-init[640]: Traceback (most recent call last):
[    7.557951] cloud-init[640]:   File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 958, in _pkl_load
[    7.559545] cloud-init[640]:     return pickle.loads(pickle_contents)
[    7.568428] cloud-init[640]: EOFError: Ran out of input
[    7.569383] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,276 - stages.py[DEBUG]: no cache found
[    7.571186] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,276 - handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: no cache found
[    7.574352] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,276 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
[    7.576273] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,282 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
[    7.577927] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,284 - __init__.py[DEBUG]: Looking for data source in: ['NoCloud', 'ConfigDrive', 'OpenNebula', 'DigitalOcean', 'Azure', 'AltCloud', 'OVF', 'MAAS', 'GCE', 'OpenStack', 'CloudSigma', 'SmartOS', 'Bigstep', 'Scaleway', 'AliYun', 'Ec2', 'CloudStack', 'Exoscale', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
[    7.590884] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,344 - util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
[    7.592554] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,344 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
[    7.620213] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,373 - __init__.py[DEBUG]: Searching for local data source in: ['DataSourceNoCloud', 'DataSourceConfigDrive', 'DataSourceOpenNebula', 'DataSourceDigitalOcean', 'DataSourceAzure', 'DataSourceOVF', 'DataSourceOpenStackLocal', 'DataSourceCloudSigma', 'DataSourceSmartOS', 'DataSourceScaleway', 'DataSourceEc2Local']
[    7.624770] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,374 - handlers.py[DEBUG]: start: init-local/search-NoCloud: searching for local data from DataSourceNoCloud
[    7.627492] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,374 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceNoCloud.DataSourceNoCloud'>
[    7.631663] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,378 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
[    7.634162] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,378 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
[    7.637066] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,388 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
[    7.641093] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,394 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
[    7.645122] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,398 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
[    7.647230] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,399 - util.py[DEBUG]: Read 176 bytes from /proc/1/environ
[    7.649293] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,399 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
[    7.651643] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,400 - util.py[DEBUG]: Read 927 bytes from /proc/self/status
[    7.653517] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,401 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
[    7.661543] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,401 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_serial (quiet=False)
[    7.663443] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,401 - util.py[DEBUG]: Read 2 bytes from /sys/class/dmi/id/product_serial
[    7.665207] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,403 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_serial returned 0
[    7.666997] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,403 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/user-data (quiet=False)
[    7.668893] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,403 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/meta-data (quiet=False)
[    7.670429] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,403 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/vendor-data (quiet=False)
[    7.681958] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,405 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/network-config (quiet=False)
[    7.684461] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,405 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/user-data (quiet=False)
[    7.692562] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,405 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/meta-data (quiet=False)
[    7.694669] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,405 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/vendor-data (quiet=False)
[    7.696615] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,407 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/network-config (quiet=False)
[    7.698739] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,407 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr0'] with allowed return codes [0, 2] (shell=False, capture=True)
[    7.704345] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,410 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr1'] with allowed return codes [0, 2] (shell=False, capture=True)
[    7.708945] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,415 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=vfat', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
[    7.710982] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,432 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
[    7.713606] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,434 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=CIDATA', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
[    7.724611] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,440 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=cidata', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
[    7.728108] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,442 - DataSourceNoCloud.py[DEBUG]: Attempting to use data from /dev/sdb
[    7.731036] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,442 - util.py[DEBUG]: Reading from /proc/mounts (quiet=False)
[    7.733831] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,443 - util.py[DEBUG]: Read 1978 bytes from /proc/mounts
[    7.736378] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,443 - util.py[DEBUG]: Fetched {'udev': {'opts': 'rw,nosuid,relatime,size=498576k,nr_inodes=124644,mode=755', 'fstype': 'devtmpfs', 'mountpoint': '/dev'}, 'mqueue': {'opts': 'rw,relatime', 'fstype': 'mqueue', 'mountpoint': '/dev/mqueue'}, 'tmpfs': {'opts': 'ro,nosuid,nodev,noexec,mode=755', 'fstype': 'tmpfs', 'mountpoint': '/sys/fs/cgroup'}, 'pstore': {'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'pstore', 'mountpoint': '/sys/fs/pstore'}, 'hugetlbfs': {'opts': 'rw,relatime', 'fstype': 'hugetlbfs', 'mountpoint': '/dev/hugepages'}, 'sysfs': {'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'sysfs', 'mountpoint': '/sys'}, 'debugfs': {'opts': 'rw,relatime', 'fstype': 'debugfs', 'mountpoint': '/sys/kernel/debug'}, 'cgroup': {'opts': 'rw,nosuid,nodev,noexec,relatime,net_cls,net_prio', 'fstype': 'cgroup', 'mountpoint': '/sys/fs/cgroup/net_cls,net_prio'}, 'devpts': {'opts': 'rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000', 'fstype': 'devpts', 'mountpoint': '/dev/pts'}, '/dev/sda1': {'opts': 'rw,relatime,data=ordered', 'fstype': 'ext4', 'mountpoint': '/'}, 'fusectl': {'opts': 'rw,relatime', 'fstype': 'fusectl', 'mountpoint': '/sys/fs/fuse/connections'}, 'systemd-1': {'opts': 'rw,relatime,fd=26,pgrp=1,timeout=0,minproto=5,maxproto=5,direct', 'fstype': 'autofs', 'mountpoint': '/proc/sys/fs/binfmt_misc'}, 'securityfs': {'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'securityfs', 'mountpoint': '/sys/kernel/security'}, 'proc': {'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'proc', 'mountpoint': '/proc'}} mounts from proc
[    7.759807] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,443 - util.py[DEBUG]: Running command ['mount', '-o', 'ro', '-t', 'auto', '/dev/sdb', '/run/cloud-init/tmp/tmpoh3pp_yu'] with allowed return codes [0] (shell=False, capture=True)
[    7.764315] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,472 - util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpoh3pp_yu//user-data (quiet=False)
[    7.767665] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,473 - util.py[DEBUG]: Read 42 bytes from /run/cloud-init/tmp/tmpoh3pp_yu//user-data
[    7.770596] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,473 - util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpoh3pp_yu//meta-data (quiet=False)
[    7.773591] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,474 - util.py[DEBUG]: Read 64 bytes from /run/cloud-init/tmp/tmpoh3pp_yu//meta-data
[    7.776164] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,474 - util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpoh3pp_yu//vendor-data (quiet=False)
[    7.779641] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,474 - util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpoh3pp_yu//network-config (quiet=False)
[    7.782994] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,474 - util.py[DEBUG]: Running command ['umount', '/run/cloud-init/tmp/tmpoh3pp_yu'] with allowed return codes [0] (shell=False, capture=True)
[    7.786589] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,487 - util.py[DEBUG]: Attempting to load yaml from string of length 64 with allowed root types (<class 'dict'>,)
[    7.790079] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,512 - DataSourceNoCloud.py[DEBUG]: Using data from /dev/sdb
[    7.792624] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,514 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmph12j_n3m) - w: [644] 756 bytes/chars
[    7.796103] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,518 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmpk4qb1fhe) - w: [600] 756 bytes/chars
[    7.799572] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,521 - handlers.py[DEBUG]: finish: init-local/search-NoCloud: SUCCESS: found local data from DataSourceNoCloud
[    7.803039] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,521 - stages.py[INFO]: Loaded datasource DataSourceNoCloud - DataSourceNoCloud [seed=/dev/sdb][dsmode=net]
[    7.805957] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,521 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
[    7.808208] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,524 - util.py[DEBUG]: Read 3612 bytes from /etc/cloud/cloud.cfg
[    7.810509] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,524 - util.py[DEBUG]: Attempting to load yaml from string of length 3612 with allowed root types (<class 'dict'>,)
[    7.820545] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,574 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
[    7.828577] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,574 - util.py[DEBUG]: Read 248 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
[    7.830250] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,574 - util.py[DEBUG]: Attempting to load yaml from string of length 248 with allowed root types (<class 'dict'>,)
[    7.833539] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,577 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
[    7.835454] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,578 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
[    7.837625] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,578 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
[    7.839466] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,581 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
[    7.840961] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,582 - util.py[DEBUG]: Read 48 bytes from /run/cloud-init/cloud.cfg
[    7.842655] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,582 - util.py[DEBUG]: Attempting to load yaml from string of length 48 with allowed root types (<class 'dict'>,)
[    7.844660] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,584 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
[    7.846676] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,584 - util.py[DEBUG]: loaded blob returned None, returning default.
[    7.848442] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,589 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
[    7.856498] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,589 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/iid-b58ffe1bc40a19a8'
[    7.858825] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,593 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/iid-b58ffe1bc40a19a8/datasource (quiet=False)
[    7.868833] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,596 - util.py[DEBUG]: Read 65 bytes from /var/lib/cloud/instances/iid-b58ffe1bc40a19a8/datasource
[    7.870837] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,596 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-b58ffe1bc40a19a8/datasource - wb: [644] 65 bytes
[    7.873224] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,602 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 65 bytes
[    7.875549] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,604 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
[    7.877666] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,604 - util.py[DEBUG]: Read 21 bytes from /var/lib/cloud/data/instance-id
[    7.879655] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,604 - stages.py[DEBUG]: previous iid found to be iid-b58ffe1bc40a19a8
[    7.881110] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,605 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 21 bytes
[    7.883019] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,605 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 21 bytes
[    7.884967] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,605 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 21 bytes
[    7.886757] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,606 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 6989 bytes
[    7.900586] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,607 - main.py[DEBUG]: [local] init will now be targeting instance id: iid-b58ffe1bc40a19a8. new=False
[    7.902626] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,607 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
[    7.905084] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,607 - util.py[DEBUG]: Read 3612 bytes from /etc/cloud/cloud.cfg
[    7.908295] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,607 - util.py[DEBUG]: Attempting to load yaml from string of length 3612 with allowed root types (<class 'dict'>,)
[    7.912349] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,622 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
[    7.914521] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,622 - util.py[DEBUG]: Read 248 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
[    7.916462] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,622 - util.py[DEBUG]: Attempting to load yaml from string of length 248 with allowed root types (<class 'dict'>,)
[    7.920302] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,629 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
[    7.922266] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,631 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
[    7.924220] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,631 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
[    7.926502] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,643 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
[    7.928504] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,643 - util.py[DEBUG]: Read 48 bytes from /run/cloud-init/cloud.cfg
[    7.931132] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,643 - util.py[DEBUG]: Attempting to load yaml from string of length 48 with allowed root types (<class 'dict'>,)
[    7.934027] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,644 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
[    7.936458] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,644 - util.py[DEBUG]: loaded blob returned None, returning default.
[    7.938860] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,644 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
[    7.941344] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,644 - util.py[DEBUG]: Read 78 bytes from /var/lib/cloud/instance/cloud-config.txt
[    7.943680] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,644 - util.py[DEBUG]: Attempting to load yaml from string of length 78 with allowed root types (<class 'dict'>,)
[    7.946191] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,645 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
[    7.956809] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,646 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
[    7.960725] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,648 - util.py[DEBUG]: Read 59 bytes from /var/lib/cloud/data/set-hostname
[    7.964593] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,649 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
[    7.966959] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,649 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
[    7.969226] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,649 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
[    7.971230] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,649 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
[    7.973605] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,649 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
[    7.975710] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,650 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/name_assign_type (quiet=False)
[    7.978221] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,650 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s3/name_assign_type
[    7.988483] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,650 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/carrier (quiet=False)
[    7.992331] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,650 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/dormant (quiet=False)
[    7.994773] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,651 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/operstate (quiet=False)
[    7.997218] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,651 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/enp0s3/operstate
[    7.999550] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,651 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
[    8.001349] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,651 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
[    8.003559] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,651 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
[    8.005602] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,651 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
[    8.007810] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,651 - __init__.py[DEBUG]: Datasource DataSourceNoCloud [seed=/dev/sdb][dsmode=net] not updated for events: System boot
[    8.016345] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,651 - stages.py[DEBUG]: No network config applied. Neither a new instance nor datasource network update on 'System boot' event
[    8.018411] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,652 - stages.py[DEBUG]: applying net config names for {'version': 2, 'ethernets': {'enp0s3': {'match': {'macaddress': '02:dd:a3:75:e5:c1'}, 'set-name': 'enp0s3', 'dhcp4': True}}}
[    8.021188] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,652 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/device/device (quiet=False)
[    8.023177] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,652 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/enp0s3/device/device
[    8.025092] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,652 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/addr_assign_type (quiet=False)
[    8.027258] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,652 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s3/addr_assign_type
[    8.029334] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,652 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/uevent (quiet=False)
[    8.036428] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,652 - util.py[DEBUG]: Read 27 bytes from /sys/class/net/enp0s3/uevent
[    8.044642] [[0;1;31mFAILED[0m] Failed to start Initial cloud-init job (pre-networking).
See 'systemctl status cloud-init-local.service' for details.
[[0;32m  OK  [0m] Reached target Network (Pre).
cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,653 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
[    8.048793] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,653 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
[    8.056946]          Starting Raise network interfaces...
cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,653 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/device/device (quiet=False)[[0;32m  OK  [0m] Started ifup for enp0s3.

[    8.059484] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,653 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/enp0s3/device/device
[    8.063993] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,653 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
[    8.068657] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,653 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
[    8.070734] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,653 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
[    8.072384] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,653 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
[    8.074138] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,653 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
[    8.076127] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,653 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
[    8.084609] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,654 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
[    8.087128] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,654 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/operstate (quiet=False)
[    8.089223] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,654 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/enp0s3/operstate
[    8.092258] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,654 - util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
[    8.094517] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,654 - util.py[DEBUG]: Read 8 bytes from /sys/class/net/lo/operstate
[    8.096530] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,656 - util.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
[    8.105042] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,666 - util.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
[    8.107212] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,678 - __init__.py[DEBUG]: no work necessary for renaming of [['02:dd:a3:75:e5:c1', 'enp0s3', 'e1000', '0x100e']]
[    8.116725] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,679 - main.py[DEBUG]: [local] Exiting. datasource DataSourceNoCloud [seed=/dev/sdb][dsmode=net] not in local mode.
[    8.124652] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,679 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpw2uy8a86) - w: [644] 517 bytes/chars
[    8.128517] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,679 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
[    8.136265] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,680 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
[    8.137597] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,680 - util.py[DEBUG]: cloud-init mode 'init' took 0.449 seconds (0.45)
[    8.139172] cloud-init[640]: FALLBACK: 2020-05-22 07:25:30,680 - handlers.py[DEBUG]: finish: init-local: FAIL: searching for local datasources
[    8.148379] cloud-init[640]: OSError: [Errno 28] No space left on device
[    8.149462] cloud-init[640]: During handling of the above exception, another exception occurred:
[    8.150577] cloud-init[640]: Traceback (most recent call last):
[    8.151498] cloud-init[640]:   File "/usr/bin/cloud-init", line 9, in <module>
[    8.160308] cloud-init[640]:     load_entry_point('cloud-init==19.3', 'console_scripts', 'cloud-init')()
[    8.163576] cloud-init[640]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 893, in main
[    8.166069] cloud-init[640]:     get_uptime=True, func=functor, args=(name, args))
[    8.167956] cloud-init[640]:   File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2539, in log_time
[    8.171347] cloud-init[640]:     ret = func(*args, **kwargs)
[    8.173452] cloud-init[640]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 671, in status_wrapper
[    8.176514] cloud-init[640]:     atomic_helper.write_json(status_path, status)
[    8.178462] cloud-init[640]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 46, in write_json
[    8.180575] cloud-init[640]:     omode="w", mode=mode)
[    8.183145] cloud-init[640]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 39, in write_file
[    8.188816] cloud-init[640]:     raise e
[    8.191550] cloud-init[640]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 33, in write_file
[    8.195184] cloud-init[640]:     tf.close()
[    8.204287] cloud-init[640]:   File "/usr/lib/python3.5/tempfile.py", line 648, in close
[    8.212336] cloud-init[640]:     self._closer.close()
[    8.213328] cloud-init[640]:   File "/usr/lib/python3.5/tempfile.py", line 582, in close
[    8.214078] cloud-init[640]:     self.file.close()
[    8.215125] cloud-init[640]: OSError: [Errno 28] No space left on device
[    8.216475] cloud-init[640]: Error in sys.excepthook:
[    8.217573] cloud-init[640]: Traceback (most recent call last):
[    8.219471] cloud-init[640]:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 146, in apport_excepthook
[    8.221500] cloud-init[640]:     pr.write(f)
[    8.222238] cloud-init[640]:   File "/usr/lib/python3/dist-packages/problem_report.py", line 402, in write
[    8.223864] cloud-init[640]:     file.write(v.replace(b'\n', b'\n '))
[    8.224923] cloud-init[640]: OSError: [Errno 28] No space left on device
[    8.232564] cloud-init[640]: During handling of the above exception, another exception occurred:
[    8.233594] cloud-init[640]: Traceback (most recent call last):
[    8.240724] [cloud-init[0;32m  OK  [0m[640]: ]   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 146, in apport_excepthookStarted Raise network interfaces.

[    8.243159] [[0;32m  OK  [0m] Reached target Network.
cloud-init[640]:     pr.write(f)
[    8.244878] cloud-init[640]: OSError: [Errno 28] No space left on device
[    8.252940] cloud-init[640]: Original exception was:
[    8.264766]          Starting Initial cloud-init job (metadata service crawler)...
cloud-init[640]: OSError: [Errno 28] No space left on device
[    8.272823] cloud-init[640]: During handling of the above exception, another exception occurred:
[    8.274041] cloud-init[640]: Traceback (most recent call last):
[    8.280769] cloud-init[640]:   File "/usr/bin/cloud-init", line 9, in <module>
[    8.281628] cloud-init[640]:     load_entry_point('cloud-init==19.3', 'console_scripts', 'cloud-init')()
[    8.288376] cloud-init[640]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 893, in main
[    8.289814] cloud-init[640]:     get_uptime=True, func=functor, args=(name, args))
[    8.296622] cloud-init[640]:   File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2539, in log_time
[    8.304812] cloud-init[640]:     ret = func(*args, **kwargs)
[    8.305965] cloud-init[640]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 671, in status_wrapper
[    8.312558] cloud-init[640]:     atomic_helper.write_json(status_path, status)
[    8.320772] cloud-init[640]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 46, in write_json
[    8.322410] cloud-init[640]:     omode="w", mode=mode)
[    8.332496] cloud-init[640]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 39, in write_file
[    8.333922] cloud-init[640]:     raise e
[    8.340702] cloud-init[640]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 33, in write_file
[    8.348456] cloud-init[640]:     tf.close()
[    8.349680] cloud-init[640]:   File "/usr/lib/python3.5/tempfile.py", line 648, in close
[    8.360563] cloud-init[640]:     self._closer.close()
[    8.368556] cloud-init[640]:   File "/usr/lib/python3.5/tempfile.py", line 582, in close
[    8.370064] cloud-init[640]:     self.file.close()
[    8.376526] cloud-init[640]: OSError: [Errno 28] No space left on device
[    8.529500] cloud-init[984]: OSError: [Errno 28] No space left on device
[    8.530736] cloud-init[984]: During handling of the above exception, another exception occurred:
[    8.531895] cloud-init[984]: Traceback (most recent call last):
[    8.532992] cloud-init[984]:   File "/usr/bin/cloud-init", line 9, in <module>
[    8.534270] cloud-init[984]:     load_entry_point('cloud-init==19.3', 'console_scripts', 'cloud-init')()
[    8.536012] cloud-init[984]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 893, in main
[    8.537972] cloud-init[984]:     get_uptime=True, func=functor, args=(name, args))
[    8.539427] cloud-init[984]:   File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2539, in log_time
[    8.544824] cloud-init[984]:     ret = func(*args, **kwargs)
[    8.552832] cloud-init[984]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 648, in status_wrapper
[    8.554783] cloud-init[984]:     atomic_helper.write_json(status_path, status)
[    8.564633] cloud-init[984]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 46, in write_json
[    8.572708] cloud-init[984]:     omode="w", mode=mode)
[    8.584751] cloud-init[984]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 39, in write_file
[    8.588592] [[0;1;31mFAILED[0m] Failed to start Initial cloud-init job (metadata service crawler).
See 'systemctl status cloud-init.service' for details.
[[0;32m  OK  [0m] Reached target System Initialization.
cloud-init[984]:     raise e
[    8.596679] cloud-init[[0;32m  OK  [0m] Started ACPI Events Check.
[[0;32m  OK  [0m] Reached target Paths.
         Starting LXD - unix socket.
[984]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 33, in write_file[[0;32m  OK  [0m] Started Message of the Day.
[
[0;32m  OK  [0m] Started Daily Cleanup of Temporary Directories.
[    8.601101]          Starting Socket activation for snappy daemon.
[[0;32m  OK  [0m] Listening on D-Bus System Message Bus Socket.
[[0;32m  OK  [0m] Listening on ACPID Listen Socket.
[[0;32m  OK  [0m] Started Daily apt download activities.
cloud-init[984]:     tf.close()
[    8.604624] [[0;32m  OK  [0m] Started Daily apt upgrade and clean activities.
[[0;32m  OK  [0m] Reached target Timers.
[[0;32m  OK  [0m] Listening on UUID daemon activation socket.
[[0;32m  OK  [0m] Reached target Network is Online.
cloud-init[984]:   File "/usr/lib/python3.5/tempfile.py", line 648, in close
[    8.608787] cloud-init[984]:     self._closer.close()
[    8.609977] cloud-init[984]:   File "/usr/lib/python3.5/tempfile.py", line 582, in close
[    8.611481] cloud-init[984]:     self.file.close()
[    8.620290]          Starting iSCSI initiator daemon (iscsid)...
[[0;32m  OK  [0m] Reached target Cloud-config availability.
[[0;32m  OK  [0m] Listening on LXD - unix socket.
[[0;32m  OK  [0m] Listening on Socket activation for snappy daemon.
cloud-init[984]: OSError: [Errno 28] No space left on device
[    8.623774] [[0;32m  OK  [0m] Reached target Sockets.
[[0;32m  OK  [0m] Reached target Basic System.
cloud-init[984]: Error in sys.excepthook:
[    8.626523]          Starting Login Service...
cloud-init[984]: Traceback (most recent call last):
         Starting LXD - container startup/shutdown...
[    8.629854] cloud-init[984]:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 146, in apport_excepthook
         Starting Accounts Service...
[    8.633552]          Starting LSB: MD monitoring daemon...
cloud-init[984]:     pr.write(f)
[    8.638462] cloud-init[984]:   File "/usr/lib/python3/dist-packages/problem_report.py", line 402, in write
[    8.641262] cloud-init[984]:     file.write(v.replace(b'\n', b'\n '))
[    8.643083] cloud-init[984]: OSError: [Errno 28] No space left on device
[    8.645220] cloud-init[984]: During handling of the above exception, another exception occurred:
[    8.648425] cloud-init[984]: Traceback (most recent call last):
[    8.650427] cloud-init[984]:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 146, in apport_excepthook
[    8.653244] cloud-init[984]:     pr.write(f)
[    8.655213] cloud-init[984]: OSError: [Errno 28] No space left on device
[    8.657160] cloud-init[984]: Original exception was:
[    8.658357] cloud-init[984]: OSError: [Errno 28] No space left on device
[    8.659470] cloud-init[984]: During handling of the above exception, another exception occurred:[[0;32m  OK  [0m] Started Deferred execution scheduler.
         Starting System Logging Service...

[    8.662571] [[0;32m  OK  [0m] Started Regular background program processing daemon.
[[0;32m  OK  [0m] Started D-Bus System Message Bus.
cloud-init[984]: Traceback (most recent call last):
[    8.664632] cloud-init[984]:   File "/usr/bin/cloud-init", line 9, in <module>
[    8.670218] cloud-init[984]:     load_entry_point('cloud-init==19.3', 'console_scripts', 'cloud-init')()
[    8.674418] cloud-init[984]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 893, in main
[    8.677338] cloud-init[984]:     get_uptime=True, func=functor, args=(name, args))
[    8.679195] cloud-init[984]:   File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2539, in log_time
[    8.681313] cloud-init[984]:     ret = func(*args, **kwargs)
[    8.682846] cloud-init[984]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 648, in status_wrapper
[    8.685490] cloud-init[984]:     atomic_helper.write_json(status_path, status)
[    8.686903] cloud-init[984]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 46, in write_json
[    8.696446] cloud-init[984]:     omode="w", mode=mode)
[    8.699035] cloud-init[984]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 39, in write_file
[    8.702765] cloud-init[984]:     raise e
[    8.705162] cloud-init[984]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 33, in write_file
[    8.707382] cloud-init[984]:     tf.close()
[    8.708679] cloud-init[984]:   File "/usr/lib/python3.5/tempfile.py", line 648, in close
[    8.710126] cloud-init[984]:     self._closer.close()
[    8.711446] cloud-init[984]:   File "/usr/lib/python3.5/tempfile.py", line 582, in close[[0;32m  OK  [0m] Started ACPI event daemon.

         Starting /etc/rc.local Compatibility...
[    8.714660]          Starting Message of the Day...
[[0;32m  OK  [0m] Started FUSE filesystem for LXC.
         Starting LSB: Record successful boot for GRUB...
cloud-init[984]:     self.file.close()
         Starting OpenBSD Secure Shell server...
         Starting Snappy daemon...
         Starting Virtualbox guest utils...
[[0;32m  OK  [0m] Started System Logging Service.
[[0;32m  OK  [0m] Started iSCSI initiator daemon (iscsid).
[[0;32m  OK  [0m] Started /etc/rc.local Compatibility.
[    8.733433] cloud-init[984]: OSError: [Errno 28] No space left on device
[[0;32m  OK  [0m] Started Login Service.
[[0;32m  OK  [0m] Started Unattended Upgrades Shutdown.
         Starting Authenticate and Authorize Users to Run Privileged Tasks...
         Starting Login to default iSCSI targets...
[[0;32m  OK  [0m] Started Login to default iSCSI targets.
[[0;32m  OK  [0m] Reached target Remote File Systems (Pre).
[[0;32m  OK  [0m] Reached target Remote File Systems.
         Starting LSB: Set the CPU Frequency Scaling governor to "ondemand"...
         Starting LSB: daemon to balance interrupts for SMP systems...
         Starting Permit User Sessions...
         Starting LSB: automatic crash report generation...
[[0;32m  OK  [0m] Started LSB: MD monitoring daemon.
[[0;32m  OK  [0m] Started Permit User Sessions.
[[0;32m  OK  [0m] Started LSB: Record successful boot for GRUB.
[[0;32m  OK  [0m] Started LXD - container startup/shutdown.
[[0;32m  OK  [0m] Started OpenBSD Secure Shell server.
[[0;32m  OK  [0m] Started Authenticate and Authorize Users to Run Privileged Tasks.
[[0;32m  OK  [0m] Started Accounts Service.
[[0;32m  OK  [0m] Started LSB: Set the CPU Frequency Scaling governor to "ondemand".
         Starting Terminate Plymouth Boot Screen...
         Starting Hold until boot process finishes up...
[[0;32m  OK  [0m] Started LSB: daemon to balance interrupts for SMP systems.
[[0;32m  OK  [0m] Started LSB: automatic crash report generation.
[[0;32m  OK  [0m] Started Terminate Plymouth Boot Screen.
[[0;32m  OK  [0m] Started Hold until boot process finishes up.
[[0;32m  OK  [0m] Started Getty on tty1.
         Starting Set console scheme...
[[0;32m  OK  [0m] Started Serial Getty on ttyS0.
[[0;32m  OK  [0m] Reached target Login Prompts.
[[0;32m  OK  [0m] Started Virtualbox guest utils.
[[0;32m  OK  [0m] Started Set console scheme.
[[0;32m  OK  [0m] Started Snappy daemon.
         Starting Wait until snapd is fully seeded...
[[0;32m  OK  [0m] Started Wait until snapd is fully seeded.
         Starting Apply the settings specified in cloud-config...
[[0;32m  OK  [0m] Reached target Multi-User System.
[[0;32m  OK  [0m] Reached target Graphical Interface.
         Starting Update UTMP about System Runlevel Changes...
[[0;32m  OK  [0m] Started Update UTMP about System Runlevel Changes.
[    9.416843] cloud-init[1227]: OSError: [Errno 28] No space left on device
[    9.418285] cloud-init[1227]: During handling of the above exception, another exception occurred:
[    9.420008] cloud-init[1227]: Traceback (most recent call last):
[    9.421292] cloud-init[1227]:   File "/usr/bin/cloud-init", line 9, in <module>
[    9.428936] cloud-init[1227]:     load_entry_point('cloud-init==19.3', 'console_scripts', 'cloud-init')()
[    9.430547] cloud-init[1227]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 893, in main
[    9.440783] cloud-init[1227]:     get_uptime=True, func=functor, args=(name, args))
[    9.448806] cloud-init[1227]:   File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2539, in log_time
[    9.450516] cloud-init[1227]:     ret = func(*args, **kwargs)
[    9.464231] [[0;1;31mFAILED[0m] Failed to start Apply the settings specified in cloud-config.
See 'systemctl status cloud-config.service' for details.
cloud-init[1227]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 648, in status_wrapper
[    9.472806] cloud-init[1227]:     atomic_helper.write_json(status_path, status)
[    9.474366] cloud-init[1227]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 46, in write_json
[    9.475806] cloud-init         Starting Execute cloud user/final scripts...
[1227]:     omode="w", mode=mode)
[    9.477765] cloud-init[1227]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 39, in write_file
[    9.479716] cloud-init[1227]:     raise e
[    9.480789] cloud-init[1227]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 33, in write_file
[    9.482853] cloud-init[1227]:     tf.close()
[    9.488286] cloud-init[1227]:   File "/usr/lib/python3.5/tempfile.py", line 648, in close
[    9.496712] cloud-init[1227]:     self._closer.close()
[    9.497758] cloud-init[1227]:   File "/usr/lib/python3.5/tempfile.py", line 582, in close
[    9.499152] cloud-init[1227]:     self.file.close()
[    9.500210] cloud-init[1227]: OSError: [Errno 28] No space left on device
[    9.501578] cloud-init[1227]: Error in sys.excepthook:
[    9.502664] cloud-init[1227]: Traceback (most recent call last):
[    9.508311] cloud-init[1227]:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 146, in apport_excepthook
[    9.516825] cloud-init[1227]:     pr.write(f)
[    9.517721] cloud-init[1227]:   File "/usr/lib/python3/dist-packages/problem_report.py", line 402, in write
[    9.519356] cloud-init[1227]:     file.write(v.replace(b'\n', b'\n '))
[    9.521117] cloud-init[1227]: OSError: [Errno 28] No space left on device
[    9.528309] cloud-init[1227]: During handling of the above exception, another exception occurred:
[    9.529467] cloud-init[1227]: Traceback (most recent call last):
[    9.536302] cloud-init[1227]:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 146, in apport_excepthook
[    9.537950] cloud-init[1227]:     pr.write(f)
[    9.538907] cloud-init[1227]: OSError: [Errno 28] No space left on device
[    9.540349] cloud-init[1227]: Original exception was:
[    9.548341] cloud-init[1227]: OSError: [Errno 28] No space left on device
[    9.549597] cloud-init[1227]: During handling of the above exception, another exception occurred:
[    9.551061] cloud-init[1227]: Traceback (most recent call last):
[    9.552222] cloud-init[1227]:   File "/usr/bin/cloud-init", line 9, in <module>
[    9.553475] cloud-init[1227]:     load_entry_point('cloud-init==19.3', 'console_scripts', 'cloud-init')()
[    9.560313] cloud-init[1227]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 893, in main
[    9.561581] cloud-init[1227]:     get_uptime=True, func=functor, args=(name, args))
[    9.562856] cloud-init[1227]:   File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2539, in log_time
[    9.564392] cloud-init[1227]:     ret = func(*args, **kwargs)
[    9.572268] cloud-init[1227]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 648, in status_wrapper
[    9.573841] cloud-init[1227]:     atomic_helper.write_json(status_path, status)
[    9.575055] cloud-init[1227]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 46, in write_json
[    9.584656] cloud-init[1227]:     omode="w", mode=mode)
[    9.594264] cloud-init[1227]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 39, in write_file
[    9.595943] cloud-init[1227]:     raise e
[    9.597033] cloud-init[1227]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 33, in write_file
[    9.598604] cloud-init[1227]:     tf.close()
[    9.599660] cloud-init[1227]:   File "/usr/lib/python3.5/tempfile.py", line 648, in close
[    9.601106] cloud-init[1227]:     self._closer.close()
[    9.602241] cloud-init[1227]:   File "/usr/lib/python3.5/tempfile.py", line 582, in close
[    9.603824] cloud-init[1227]:     self.file.close()
[    9.605040] cloud-init[1227]: OSError: [Errno 28] No space left on device
[    9.748137] cloud-init[1243]: OSError: [Errno 28] No space left on device
[    9.749615] cloud-init[1243]: During handling of the above exception, another exception occurred:
[    9.750912] cloud-init[1243]: Traceback (most recent call last):
[    9.752464] cloud-init[1243]:   File "/usr/bin/cloud-init", line 9, in <module>
[    9.760355] cloud-init[1243]:     load_entry_point('cloud-init==19.3', 'console_scripts', 'cloud-init')()
[    9.761735] cloud-init[1243]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 893, in main
[    9.763571] cloud-init[1243]:     get_uptime=True, func=functor, args=(name, args))
[    9.772534] cloud-init[1243]:   File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2539, in log_time
[    9.774288] cloud-init[1243]:     ret = func(*args, **kwargs)
[    9.775556] cloud-init[1243]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 648, in status_wrapper
[    9.777260] cloud-init[1243]:     atomic_helper.write_json(status_path, status)
[    9.778748] cloud-init[1243]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 46, in write_json
[    9.780712] cloud-init[1243]: [[0;1;31mFAILED[0m] Failed to start Execute cloud user/final scripts.
See 'systemctl status cloud-final.service' for details.
[[0;32m  OK  [0m] Reached target Cloud-init target.
    omode="w", mode=mode)
[    9.785242] cloud-init[1243]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 39, in write_file
[    9.792654] cloud-init[1243]:     raise e
         Starting Daily apt download activities...
[    9.796110] cloud-init[1243]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 33, in write_file
[    9.801715] cloud-init[1243]:     tf.close()
[    9.802922] cloud-init[1243]:   File "/usr/lib/python3.5/tempfile.py", line 648, in close
[    9.804796] cloud-init[1243]:     self._closer.close()
[    9.812266] cloud-init[1243]:   File "/usr/lib/python3.5/tempfile.py", line 582, in close
[    9.820462] cloud-init[1243]:     self.file.close()
[    9.821494] cloud-init[1243]: OSError: [Errno 28] No space left on device
[    9.822412] cloud-init[1243]: Error in sys.excepthook:
[    9.823237] cloud-init[1243]: Traceback (most recent call last):
[    9.828409] cloud-init[1243]:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 146, in apport_excepthook
[    9.840502] cloud-init[1243]:     pr.write(f)
[    9.848290] cloud-init[1243]:   File "/usr/lib/python3/dist-packages/problem_report.py", line 402, in write
[    9.849768] cloud-init[1243]:     file.write(v.replace(b'\n', b'\n '))
[    9.850807] cloud-init[1243]: OSError: [Errno 28] No space left on device
[    9.851908] cloud-init[1243]: During handling of the above exception, another exception occurred:
[    9.860811] cloud-init[1243]: Traceback (most recent call last):
[    9.861789] cloud-init[1243]:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 146, in apport_excepthook
[    9.863204] cloud-init[1243]:     pr.write(f)
[    9.864123] cloud-init[1243]: OSError: [Errno 28] No space left on device
[    9.865194] cloud-init[1243]: Original exception was:
[    9.866271] cloud-init[1243]: OSError: [Errno 28] No space left on device
[    9.867416] cloud-init[1243]: During handling of the above exception, another exception occurred:
[    9.868849] cloud-init[1243]: Traceback (most recent call last):
[    9.869902] cloud-init[1243]:   File "/usr/bin/cloud-init", line 9, in <module>
[    9.880379] cloud-init[1243]:     load_entry_point('cloud-init==19.3', 'console_scripts', 'cloud-init')()
[    9.881809] cloud-init[1243]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 893, in main
[    9.883995] cloud-init[1243]:     get_uptime=True, func=functor, args=(name, args))
[    9.885520] cloud-init[1243]:   File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2539, in log_time
[    9.887423] cloud-init[1243]:     ret = func(*args, **kwargs)
[    9.892917] cloud-init[1243]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 648, in status_wrapper
[    9.895117] cloud-init[1243]:     atomic_helper.write_json(status_path, status)
[    9.900873] cloud-init[1243]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 46, in write_json
[    9.902473] cloud-init[1243]:     omode="w", mode=mode)
[[0;32m  OK  [0m] Started Daily apt download activities.
[    9.909901] cloud-init[1243]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 39, in write_file
[    9.913315] cloud-init[1243]:     raise e
[    9.914237] cloud-init[1243]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 33, in write_file
[    9.920876] cloud-init[1243]:     tf.close()
[    9.921563] cloud-init[1243]:   File "/usr/lib/python3.5/tempfile.py", line 648, in close
[    9.922845] cloud-init[1243]:     self._closer.close()
         Starting Daily apt upgrade and clean activities...
[    9.935960] cloud-init[1243]:   File "/usr/lib/python3.5/tempfile.py", line 582, in close
[    9.948412] cloud-init[1243]:     self.file.close()
[    9.949413] cloud-init[1243]: OSError: [Errno 28] No space left on device
[[0;32m  OK  [0m] Started Daily apt upgrade and clean activities.
[[0;32m  OK  [0m] Started Message of the Day.

Ubuntu 16.04.6 LTS ubuntu-xenial ttyS0

ubuntu-xenial login: 